---
- name: ======================= Docker INSTALLATION =======================
  hosts: all
  become: yes
  vars_files:
    - ./majordomo-install/vars/main.yml

  roles:
    - {role: update-upgrade, when: ansible_system=='Linux'}
    - {role: majordomo-install, when: ansible_system=='Linux'}
