---
- name: ======================= Docker INSTALLATION =======================
  hosts: all
  become: yes

  roles:
    - {role: update-upgrade, when: ansible_system=='Linux'}
    - {role: majordomo-install, when: ansible_system=='Linux'}
