---
# tasks file for jenkins-install

- block: # =============== Block for Ubuntu =================

    - name: Install utils
      apt:
        pkg:
          - nano
          - wget
          - unzip
          - python3-pip

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Install MySQL
      apt:
        pkg:
          - mysql-server
          - mysql-client
          - apache2
          - apache2-utils
          - php
          - php-cgi
          - php-cli
          - php-pear
          - php-mysql
          - php-mbstring
          - php-xml
          - curl
          - libcurl4
          #          - libcurl4-dev
          - php-curl
          - libapache2-mod-php
          - phpmyadmin

    - name: Template a file to /root/.my.cnf
      ansible.builtin.template:
        src: ../templates/my.cnf.j2
        dest: /root/.my.cnf
        mode: '0644'

    - name: Create new database 'db_terminal'
      community.mysql.mysql_db:
        name:
          - db_terminal
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_host: 'localhost'
        login_user: 'root'
        login_password: '{{mysql_root_password}}'
        state: present

    # mysql_secure_installation
    - name: MySQL Secure Installation
      mysql_user:
        name: 'root'
        host_all: yes
        password: '{{mysql_root_password}}'
        login_host: 'localhost'
        login_user: 'root'
        login_password: '{{mysql_root_password}}'
        state: present

    - name: Create database user with name 'majordomo'
      community.mysql.mysql_user:
        name: majordomo
        password: '{{mysql_root_password}}'
        priv: '*.*:ALL'
        state: present